### ISSUE TITLE
ERROR: dependency 'NLMR' is not available for package 'SegOptim'

### ISSUE THREAD

**Issue by ludovico85** [joaofgoncalves/SegOptim#1]
Hi,
I'm not able to install the package due to the following error:
ERROR: dependency 'NLMR' is not available for package 'SegOptim'

Thanks in advance.

**Comment by joaofgoncalves** [comment]
NLMR is a package used for testing SegOptim so nothing very worrying. Check out the instructions to compile NLMR package from source [here](https://github.com/ropensci/NLMR).
