### ISSUE TITLE
Installation problem because of NLMR

### ISSUE THREAD

**Issue by acanion** [joaofgoncalves/SegOptim#2]
I am unable to install because of a dependency issue:

ERROR: dependency 'NLMR' is not available for package 'SegOptim'

The NLMR package appears to have been removed from CRAN in March 2021
https://cran.r-project.org/web/packages/NLMR/index.html

Is there a workaround for this?

**Comment by joaofgoncalves** [comment]
Check out this [thread](https://groups.google.com/g/segoptim-user-group/c/p-RAcKxsaTc) to solve that installation issue with the NLMR package.

**Comment by acanion** [comment]
Thank you that works
