### ISSUE TITLE
Errors in training functions, tracked to SegOptim::calcStats() and dplyr::desc()

### ISSUE THREAD

**Issue by arthurdegrandpre** [joaofgoncalves/SegOptim#7]
Hi,

I've been trying to debug the function prepareCalData(), which led me to getTrainData(), resulting in the following :

Error in as_string(x) : Can't convert a call to a string.
Error in getTrainData_(x = trainData, rstSegm = rstSegm, useThresh = TRUE,  : 
  An error occurred while calculating training data stats!

Looking into getTrainData(), the error seems to occur with the calcStats() function defined as follow, where the error occurs at the identified step.

calcStats = function (x, thresh = 0.5) 
{
    x <- dtplyr::lazy_dt(x, key_by = "SID")
    tb <- x %>%
          dplyr::group_by(.data$SID, .data$train) %>% 
          dplyr::summarize(prop = dplyr::n()) %>% 
          dplyr::mutate(rs = sum(.data$prop)) %>%
          dplyr::ungroup() %>% 
          dplyr::mutate(prop = .data$prop/.data$rs) %>%
          dplyr::select(-.data$rs) %>% 
          dplyr::filter(!is.na(.data$train)) %>% 
          dplyr::filter(.data$prop >= thresh) %>%
          dplyr::group_by(.data$SID) %>%
          **dplyr::arrange(.data$SID, dplyr::desc(.data$prop)) %>%**  # ERROR HERE
          dplyr::slice(1) %>%
          dplyr::ungroup() %>% 
          dplyr::select(-.data$prop) %>%
          as.data.frame()
    return(tb)
}

I tried updating dplyr and calling the plyr version, but neither fixed the issue.
A simple fix that seemed to work was to remove the dplyr:: call to desc() in the problematic line :

 **dplyr::arrange(.data$SID, desc(.data$prop)) %>%** 

I do not quite understand why this works but I have yet to find another solution.

Cheers,
Arthur de Grandpré

**Comment by joaofgoncalves** [comment]
Hi! Thanks @arthurdegrandpre! 👌👍 
The bug fix is working and has been released in the latest version of the package (experimental branch). I'm still not entirely sure what is happening, but issues with dplyr and dtplyr happened in the past. I will try to generate a minimal example to reproduce and report this issue.
