### ISSUE TITLE
OTB_LSMS doesn't respect minsize argument

### ISSUE THREAD

**Issue by arthurdegrandpre** [joaofgoncalves/SegOptim#8]
Hi,

Despite optimizing the input parameters to segmentation_OTB_LSMS, the minsize argument doesn't seem to prevent large numbers of small polygons (single pixel and such).

Is this caused by OTB or SegOptim? I feel like it might be caused by the call to the LSMSSmallRegionsMerging algo.

See this example based on the tutorial dataset, just adjust your otbBinPath & RAM:

#####################
#####remotes::install_github("joaofgoncalves/SegOptim", ref="experimental")

library(raster)
library(SegOptim)
library(terra)

rstClassifFeatures <- stack("./CLASSIF_FEAT/WV2_VilarVeiga_smallTestSite.tif")
segmFeatures <- "./SEGM_FEAT/WV2_b532_VilarVeiga_smallTestSite.tif"
rstTrainData <- raster("./TRAIN_AREAS/trainAreas_Adealbata_VVeiga_WV2_v1.tif")

seg = SegOptim::segmentation_OTB_LSMS(
  x = c(3.3,5.13,18),
  inputRstPath = segmFeatures,
  otbBinPath = "C:/OTB-8.1.1-Win64/bin",
  RAM = 15000)

test = as.polygons(rast(seg$Segmentation))

table(round(expanse(test)))

#################

Best,
Arthur

**Comment by joaofgoncalves** [comment]
Hi @arthurdegrandpre. Potentially this could be an issue from OTB side. Could you run also with the **segmentation_OTB_LSMS2** function and check this? This function separates mean-shift parameters from LSS ones (so two sets of parameters for each stage).

Also, OTB units in the segmentation functions and expanse units are different. Have you considered that? The first is in nr of pixels while the second should be in sq meters. Please check.

Cheers
João

**Comment by arthurdegrandpre** [comment]
Hi @joaofgoncalves ! Thanks for your answer and sorry for the long delay.
I have tried running the LSMS2 function and had the same problem. (also checked for nb pixel / area conversion)
Running the same parameters in the OTB Monteverdi GUI did work and respected the minsize argument.
I'll try to look into the SegOptim LSMS call.
Cheers!
Arthur

**Comment by joaofgoncalves** [comment]
Hello! @arthurdegrandpre thanks for checking this issue and for your time. I will gladly integrate any bug fix you may discover to correct this issue.

Cheers

**Comment by arthurdegrandpre** [comment]
Good news, everything actually works fine, so I will close this issue.

Looking at the function, I realized I was not using the proper output object.
Merged objects are located in the result$segm object, and I was looking at result$Segmentation.

I suggest adding a note in the R documentation (a sentence presenting all outputs in the Value section).

Best,
Arthur
